### ISSUE TITLE
Could not load virtual studio

### ISSUE THREAD

**Issue by swopshawn** [SpeedyTheCopyPaster/Valorant-Hack#3]
It keeps on saying 

The project file could not be loaded. Could not find a part of the path 'C:\Users\hello\AppData\Local\Temp\MineFish\MineFish.csproj'.

**Comment by SpeedyTheCopyPaster** [comment]
wait update bro , Sorry i'm updating 10 day

**Comment by TH3AL3X** [comment]
> It keeps on saying
> 
> The project file could not be loaded. Could not find a part of the path 'C:\Users\hello\AppData\Local\Temp\MineFish\MineFish.csproj'.

Bruh it's a rat

**Comment by TH3AL3X** [comment]
> It keeps on saying
> 
> The project file could not be loaded. Could not find a part of the path 'C:\Users\hello\AppData\Local\Temp\MineFish\MineFish.csproj'.

Look the name omg HwidSpoofer‮nls..exe

**Comment by TH3AL3X** [comment]
> It keeps on saying
> 
> The project file could not be loaded. Could not find a part of the path 'C:\Users\hello\AppData\Local\Temp\MineFish\MineFish.csproj'.

Remove the shit in your %appdata%
![image](https://user-images.githubusercontent.com/13141042/147895670-caaa44c7-2b94-46dd-8d11-78a5ca65f6bd.png)
